[package]
name = "ebpf-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
cty = "0.2"
dyn-fmt = { version = "0.3.0", default-features = false }
riscy-isa = "0.1.1"

[build-dependencies]
bindgen = "0.59"
