name: mdbook
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-mdbook@v1
    - run: mdbook build ./docs -d ./docs/book
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book
